# Generated by Django 4.1.1 on 2022-11-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.CharField(max_length=10)),
                ('tipo_tarea', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnogurus.curso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('postre', models.CharField(max_length=140)),
                ('cantidad', models.IntegerField()),
                ('cantidad_postre', models.IntegerField()),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnogurus.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('aula', models.CharField(max_length=10)),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnogurus.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('usuario_pictograma', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(max_length=20)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnogurus.curso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
