# Generated by Django 4.1.1 on 2022-11-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0002_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
