# Generated by Django 4.1.1 on 2022-11-24 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0002_friend_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='profile',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tecnogurus.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='tecnogurus.friend'),
        ),
    ]
