# Generated by Django 4.1.1 on 2022-12-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0004_alter_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image_list', models.CharField(max_length=20)),
                ('images_id', models.ManyToManyField(to='tecnogurus.image')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='image_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnogurus.imagelist'),
        ),
    ]
