# Generated by Django 4.1.1 on 2022-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0005_image_imagelist_tarea_image_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ruta',
        ),
        migrations.AddField(
            model_name='image',
            name='imagen',
            field=models.FileField(null=True, upload_to='static/img'),
        ),
    ]
