# Generated by Django 4.1.1 on 2022-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0006_remove_image_ruta_image_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagen',
            field=models.FileField(null=True, upload_to='img'),
        ),
    ]
