# Generated by Django 3.2.16 on 2022-12-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0007_alter_image_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='encargado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tecnogurus.alumno'),
        ),
    ]
