# Generated by Django 4.1.1 on 2022-12-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0008_tarea_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_image',
            field=models.CharField(max_length=35),
        ),
    ]
