# Generated by Django 4.1.1 on 2022-12-20 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnogurus', '0009_alter_image_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tarea',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2022, 12, 20, 16, 59, 50, 394746)),
        ),
        migrations.AddField(
            model_name='tarea',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2022, 12, 20, 16, 59, 50, 394731)),
        ),
        migrations.AddField(
            model_name='tarea',
            name='retroalimentacion',
            field=models.CharField(default='Todavia no hay correccion', max_length=140),
        ),
        migrations.AddField(
            model_name='tarea',
            name='terminado',
            field=models.BooleanField(default=True),
        ),
    ]
